# Generated by Django 4.2.5 on 2023-11-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Показ'),
        ),
    ]
