# Generated by Django 4.2.5 on 2023-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerstore', '0002_flower_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/', verbose_name='Фото цветка'),
        ),
    ]
